[project]
name = "ilae-neuroimagingschool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipyniivue>=2.4.4",
    "matplotlib>=3.10.9",
    "nibabel>=5.4.2",
    "nilearn>=0.13.1",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "pathlib>=1.0.1",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]
